### PR TITLE
adds user remove buttons, adds error with empty list

### LINKED ISSUE #9: show an error when a list has no members

### PR DESCRIPTION
**Pull request by dtemkin1**
fixes #9

### CODE REVIEW

**Comment by gabrc52** [comment]
`getDeleteData` could probably be turned into a single function to check if you are an administrator of the list, and the logged in user's kerb could be a "global" (store + getContext like the webathena token). This way, it could work in the general case, such as showing any other administrative UI (add members, edit list info, etc). Keep in mind membership admins can only edit the membership list but not other list info (a feature not currently shown by WebMoira).

**Comment by dtemkin1** [comment]
hehehe im working on reformatting the api rn >:)

**Comment by dtemkin1** [comment]
the problem im running into is that since store and getContext get passed down at initialization, im having trouble storing the promise results from the getUserInfo API request. im only really able to pass down the promise, but that doesn't really solve anything :/

**Comment by gabrc52** [comment]
See https://github.com/sipb/svelte-moira/commit/4b0ed827ef222b5884d37d956373d5e7bb3bf9ec

**Pull request merged**
